### PR TITLE
Making it work

### PR DESCRIPTION
**Pull request by jarlah**
I have copied two files, map.js and arrow-circle-double.png to src from source. I have also modified javascript-console.js to tolerate undefined json variable.

### CODE REVIEW

**Comment by jarlah** [comment]
not mine fault. Something wrong on build server

**Comment by jgoldhammer** [comment]
I will have a look at it.
Build server complains about a missing pom.xml at the parent root...

**Comment by fmaul** [comment]
@jgoldhammer can you please look if it is still needed and, if yes, how we can integrate the change?

**Comment by fmaul** [comment]
I believe this has been outdated. Please open a new issue if you have a problem, still.

**Pull request closed without merging**
